import type { CustomImportTemplate } from '../types/plugin-options';

/**
 * Default import templates shipped with the plugin.
 * These are registered via TemplateRegistryService and served via GraphQL.
 * They demonstrate the template registration system and provide
 * ready-to-use templates for common integration scenarios.
 */
export const DEFAULT_IMPORT_TEMPLATES: CustomImportTemplate[] = [
    {
        id: 'api-product-sync',
        name: 'REST API Product Sync',
        description: 'Import products from an external REST API. Supports pagination, authentication, and delta sync.',
        category: 'products',
        icon: 'globe',
        requiredFields: ['name', 'sku', 'price'],
        optionalFields: ['description', 'images', 'categories', 'stock'],
        featured: true,
        tags: ['api', 'rest', 'sync', 'integration'],
        formats: ['API'],
        definition: {
            sourceType: 'API',
            targetEntity: 'Product',
            existingRecords: 'UPDATE',
            lookupFields: ['sku'],
            fieldMappings: [
                { sourceField: 'name', targetField: 'name' },
                { sourceField: 'sku', targetField: 'sku' },
                { sourceField: 'price', targetField: 'price' },
                { sourceField: 'description', targetField: 'description' },
            ],
        },
    },
    {
        id: 'json-product-import',
        name: 'JSON Product Import',
        description: 'Import products from a JSON file with nested variant and attribute data. Handles complex product structures.',
        category: 'products',
        icon: 'file-json',
        requiredFields: ['name', 'sku', 'price'],
        optionalFields: ['description', 'slug', 'variants', 'options', 'customFields'],
        tags: ['json', 'file', 'import'],
        formats: ['JSON'],
        definition: {
            sourceType: 'FILE',
            fileFormat: 'JSON',
            targetEntity: 'Product',
            existingRecords: 'UPDATE',
            lookupFields: ['sku'],
            fieldMappings: [
                { sourceField: 'name', targetField: 'name' },
                { sourceField: 'sku', targetField: 'sku' },
                { sourceField: 'price', targetField: 'price' },
                { sourceField: 'description', targetField: 'description' },
                { sourceField: 'slug', targetField: 'slug' },
            ],
        },
    },
    {
        id: 'magento-product-csv',
        name: 'Magento Product Export (CSV)',
        description: 'Import products exported from Magento/Adobe Commerce in their standard CSV format. Maps Magento fields to Vendure entities.',
        category: 'products',
        icon: 'shopping-cart',
        requiredFields: ['name', 'sku', 'price'],
        optionalFields: ['description', 'short_description', 'url_key', 'qty', 'weight', 'visibility', 'status'],
        featured: true,
        tags: ['migration', 'magento', 'adobe-commerce'],
        formats: ['CSV'],
        definition: {
            sourceType: 'FILE',
            fileFormat: 'CSV',
            targetEntity: 'Product',
            existingRecords: 'UPDATE',
            lookupFields: ['sku'],
            fieldMappings: [
                { sourceField: 'name', targetField: 'name' },
                { sourceField: 'sku', targetField: 'sku' },
                { sourceField: 'price', targetField: 'price' },
                { sourceField: 'description', targetField: 'description' },
                { sourceField: 'url_key', targetField: 'slug' },
            ],
        },
    },
    {
        id: 'xml-product-feed',
        name: 'XML Product Feed Import',
        description: 'Import products from an XML feed. Commonly used for supplier feeds, marketplace integrations, and B2B data exchange.',
        category: 'products',
        icon: 'file-code',
        requiredFields: ['Name', 'SKU', 'Price'],
        optionalFields: ['Description', 'Category', 'ImageURL', 'Stock'],
        tags: ['xml', 'feed', 'supplier', 'b2b'],
        formats: ['XML'],
        definition: {
            sourceType: 'FILE',
            fileFormat: 'XML',
            targetEntity: 'Product',
            existingRecords: 'UPDATE',
            lookupFields: ['SKU'],
            fieldMappings: [
                { sourceField: 'Name', targetField: 'name' },
                { sourceField: 'SKU', targetField: 'sku' },
                { sourceField: 'Price', targetField: 'price' },
                { sourceField: 'Description', targetField: 'description' },
            ],
        },
    },
    {
        id: 'erp-inventory-sync',
        name: 'ERP Inventory Sync',
        description: 'Sync stock levels from an ERP system via scheduled API calls. Supports multi-warehouse inventory with safety stock.',
        category: 'inventory',
        icon: 'warehouse',
        requiredFields: ['sku', 'quantity'],
        optionalFields: ['warehouse', 'reserved', 'incoming', 'safety_stock'],
        featured: true,
        tags: ['erp', 'inventory', 'sync', 'api'],
        formats: ['API'],
        definition: {
            sourceType: 'API',
            targetEntity: 'StockLevel',
            existingRecords: 'UPDATE',
            lookupFields: ['sku'],
            fieldMappings: [
                { sourceField: 'sku', targetField: 'sku' },
                { sourceField: 'quantity', targetField: 'quantity' },
            ],
        },
    },
    {
        id: 'customer-crm-sync',
        name: 'CRM Customer Sync',
        description: 'Sync customer data from a CRM system (Salesforce, HubSpot, etc.) via API. Maps CRM contacts to Vendure customers.',
        category: 'customers',
        icon: 'users',
        requiredFields: ['email', 'firstName', 'lastName'],
        optionalFields: ['phone', 'company', 'address', 'tags', 'customFields'],
        tags: ['crm', 'sync', 'api', 'integration'],
        formats: ['API'],
        definition: {
            sourceType: 'API',
            targetEntity: 'Customer',
            existingRecords: 'UPDATE',
            lookupFields: ['email'],
            fieldMappings: [
                { sourceField: 'email', targetField: 'emailAddress' },
                { sourceField: 'firstName', targetField: 'firstName' },
                { sourceField: 'lastName', targetField: 'lastName' },
            ],
        },
    },
];

