import { StepConfigSchema } from '../../../shared/types';
import { CDC_DEFAULTS } from './types';
import { CDC_DATABASE_TYPE_OPTIONS, CDC_TRACKING_TYPE_OPTIONS } from '../../constants/adapter-schema-options';

export const CDC_EXTRACTOR_SCHEMA: StepConfigSchema = {
    groups: [
        { id: 'connection', label: 'Connection', description: 'Database connection settings' },
        { id: 'tracking', label: 'Change Tracking', description: 'How changes are detected' },
        { id: 'columns', label: 'Columns', description: 'Which columns to extract' },
        { id: 'deletes', label: 'Deletes', description: 'Soft-delete tracking' },
        { id: 'advanced', label: 'Advanced', description: 'Batch size and polling' },
    ],
    fields: [
        {
            key: 'connectionCode',
            label: 'Connection',
            description: 'Saved database connection',
            type: 'connection',
            required: true,
            group: 'connection',
        },
        {
            key: 'databaseType',
            label: 'Database Type',
            type: 'select',
            required: true,
            options: CDC_DATABASE_TYPE_OPTIONS,
            group: 'connection',
        },
        {
            key: 'table',
            label: 'Table',
            description: 'Table to poll for changes',
            type: 'string',
            required: true,
            placeholder: 'products',
            group: 'tracking',
        },
        {
            key: 'primaryKey',
            label: 'Primary Key Column',
            description: 'Primary key column of the table',
            type: 'string',
            required: true,
            placeholder: 'id',
            group: 'tracking',
        },
        {
            key: 'trackingColumn',
            label: 'Tracking Column',
            description: 'Column used to detect changes (e.g., updated_at, version)',
            type: 'string',
            required: true,
            placeholder: 'updated_at',
            group: 'tracking',
        },
        {
            key: 'trackingType',
            label: 'Tracking Type',
            type: 'select',
            required: true,
            options: CDC_TRACKING_TYPE_OPTIONS,
            group: 'tracking',
        },
        {
            key: 'columns',
            label: 'Columns',
            description: 'Specific columns to select as an array (e.g. ["id", "name"]). Leave empty for all columns.',
            type: 'json',
            group: 'columns',
        },
        {
            key: 'includeDeletes',
            label: 'Track Deletes',
            description: 'Query a soft-delete column for deleted rows',
            type: 'boolean',
            defaultValue: false,
            group: 'deletes',
        },
        {
            key: 'deleteColumn',
            label: 'Delete Column',
            description: 'Timestamp column that indicates when a row was deleted',
            type: 'string',
            placeholder: 'deleted_at',
            group: 'deletes',
            dependsOn: { field: 'includeDeletes', value: true },
        },
        {
            key: 'batchSize',
            label: 'Batch Size',
            description: 'Maximum rows per extraction',
            type: 'number',
            defaultValue: CDC_DEFAULTS.batchSize,
            group: 'advanced',
        },
        {
            key: 'pollIntervalMs',
            label: 'Poll Interval (ms)',
            description: 'Milliseconds between polls (used by scheduler)',
            type: 'number',
            defaultValue: CDC_DEFAULTS.pollIntervalMs,
            group: 'advanced',
        },
    ],
};
