import { StepConfigSchema } from '../../types/index';
import { FileFormat, SortOrder } from '../../constants/enums';
import { FILE_EXTRACTOR_DEFAULTS } from './types';
import { FILE_FORMAT_OPTIONS, CSV_DELIMITER_OPTIONS, FILE_SORT_BY_OPTIONS, SORT_ORDER_OPTIONS } from '../../constants/adapter-schema-options';

export const FILE_EXTRACTOR_SCHEMA: StepConfigSchema = {
    groups: [
        { id: 'source', label: 'Source', description: 'File source configuration' },
        { id: 'format', label: 'Format', description: 'File format options' },
        { id: 'csv', label: 'CSV Options', description: 'CSV-specific settings' },
        { id: 'json', label: 'JSON Options', description: 'JSON-specific settings' },
        { id: 'xml', label: 'XML Options', description: 'XML-specific settings' },
        { id: 'xlsx', label: 'Excel Options', description: 'Excel-specific settings' },
        { id: 'advanced', label: 'Advanced', description: 'Advanced options' },
    ],
    fields: [
        {
            key: 'path',
            label: 'File Path',
            description: 'File path or glob pattern (e.g., /data/*.csv)',
            type: 'string',
            required: true,
            placeholder: '/data/imports/*.csv',
            group: 'source',
        },
        {
            key: 'baseDir',
            label: 'Base Directory',
            description: 'Base directory for relative paths',
            type: 'string',
            placeholder: '/var/data',
            group: 'source',
        },
        {
            key: 'format',
            label: 'File Format',
            description: 'File format (auto-detected if not specified)',
            type: 'select',
            options: FILE_FORMAT_OPTIONS,
            group: 'format',
        },
        // CSV Options
        {
            key: 'csv.delimiter',
            label: 'Delimiter',
            type: 'select',
            options: CSV_DELIMITER_OPTIONS,
            defaultValue: ',',
            group: 'csv',
            dependsOn: { field: 'format', value: FileFormat.CSV },
        },
        {
            key: 'csv.header',
            label: 'Has Header Row',
            type: 'boolean',
            defaultValue: true,
            group: 'csv',
            dependsOn: { field: 'format', value: FileFormat.CSV },
        },
        {
            key: 'csv.skipEmptyLines',
            label: 'Skip Empty Lines',
            type: 'boolean',
            defaultValue: true,
            group: 'csv',
            dependsOn: { field: 'format', value: FileFormat.CSV },
        },
        // JSON Options
        {
            key: 'json.path',
            label: 'Data Path',
            description: 'JSON path to records array (e.g., data.items)',
            type: 'string',
            placeholder: 'data.items',
            group: 'json',
            dependsOn: { field: 'format', value: FileFormat.JSON },
        },
        // XML Options
        {
            key: 'xml.recordPath',
            label: 'Record Path',
            description: 'XPath-like path to record elements',
            type: 'string',
            placeholder: '//products/product',
            group: 'xml',
            dependsOn: { field: 'format', value: FileFormat.XML },
        },
        {
            key: 'xml.attributePrefix',
            label: 'Attribute Prefix',
            description: 'Prefix for XML attributes',
            type: 'string',
            defaultValue: '@',
            group: 'xml',
            dependsOn: { field: 'format', value: FileFormat.XML },
        },
        // Excel Options
        {
            key: 'xlsx.sheet',
            label: 'Sheet Name/Index',
            description: 'Sheet name or zero-based index',
            type: 'string',
            placeholder: 'Sheet1 or 0',
            group: 'xlsx',
            dependsOn: { field: 'format', value: FileFormat.XLSX },
        },
        {
            key: 'xlsx.range',
            label: 'Cell Range',
            description: 'Cell range to read (e.g., A1:Z100)',
            type: 'string',
            placeholder: 'A1:Z100',
            group: 'xlsx',
            dependsOn: { field: 'format', value: FileFormat.XLSX },
        },
        {
            key: 'xlsx.header',
            label: 'Has Header Row',
            type: 'boolean',
            defaultValue: true,
            group: 'xlsx',
            dependsOn: { field: 'format', value: FileFormat.XLSX },
        },
        // Advanced Options
        {
            key: 'modifiedAfter',
            label: 'Modified After',
            description: 'Only process files modified after this date (ISO format)',
            type: 'string',
            placeholder: '2024-01-01T00:00:00Z',
            group: 'advanced',
        },
        {
            key: 'includeFileMetadata',
            label: 'Include File Metadata',
            description: 'Add file path, size, and modified date to records',
            type: 'boolean',
            defaultValue: false,
            group: 'advanced',
        },
        {
            key: 'maxFiles',
            label: 'Max Files',
            description: 'Maximum number of files to process',
            type: 'number',
            defaultValue: FILE_EXTRACTOR_DEFAULTS.maxFiles,
            group: 'advanced',
        },
        {
            key: 'sortBy',
            label: 'Sort Files By',
            type: 'select',
            options: FILE_SORT_BY_OPTIONS,
            defaultValue: 'modified',
            group: 'advanced',
        },
        {
            key: 'sortOrder',
            label: 'Sort Order',
            type: 'select',
            options: SORT_ORDER_OPTIONS,
            defaultValue: SortOrder.ASC,
            group: 'advanced',
        },
        {
            key: 'continueOnError',
            label: 'Continue on Error',
            description: 'Continue processing if a file fails to parse',
            type: 'boolean',
            defaultValue: true,
            group: 'advanced',
        },
    ],
};
