export * from './types';
export * from './helpers';
export * from './aggregation.operators';
export * from './join.operator';

import {
    AGGREGATE_OPERATOR_DEFINITION,
    COUNT_OPERATOR_DEFINITION,
    UNIQUE_OPERATOR_DEFINITION,
    FLATTEN_OPERATOR_DEFINITION,
    FIRST_OPERATOR_DEFINITION,
    LAST_OPERATOR_DEFINITION,
    EXPAND_OPERATOR_DEFINITION,
} from './aggregation.operators';
import { MULTI_JOIN_OPERATOR_DEFINITION } from './join.operator';
import { AdapterDefinition } from '../types';

export const AGGREGATION_OPERATOR_DEFINITIONS: AdapterDefinition[] = [
    AGGREGATE_OPERATOR_DEFINITION,
    COUNT_OPERATOR_DEFINITION,
    UNIQUE_OPERATOR_DEFINITION,
    FLATTEN_OPERATOR_DEFINITION,
    FIRST_OPERATOR_DEFINITION,
    LAST_OPERATOR_DEFINITION,
    EXPAND_OPERATOR_DEFINITION,
    MULTI_JOIN_OPERATOR_DEFINITION,
];
