port 26379
protected-mode no
dir /tmp
logfile ""
sentinel monitor datahub-primary redis-primary 6379 2
sentinel down-after-milliseconds datahub-primary 3000
sentinel failover-timeout datahub-primary 10000
sentinel parallel-syncs datahub-primary 1
