export * from './types';
export * from './helpers';
export * from './string.operators';

import {
    SPLIT_OPERATOR_DEFINITION,
    JOIN_OPERATOR_DEFINITION,
    TRIM_OPERATOR_DEFINITION,
    LOWERCASE_OPERATOR_DEFINITION,
    UPPERCASE_OPERATOR_DEFINITION,
    SLUGIFY_OPERATOR_DEFINITION,
    CONCAT_OPERATOR_DEFINITION,
    REPLACE_OPERATOR_DEFINITION,
    EXTRACT_REGEX_OPERATOR_DEFINITION,
    REPLACE_REGEX_OPERATOR_DEFINITION,
    STRIP_HTML_OPERATOR_DEFINITION,
    TRUNCATE_OPERATOR_DEFINITION,
} from './string.operators';
import { AdapterDefinition } from '../types';

export const STRING_OPERATOR_DEFINITIONS: AdapterDefinition[] = [
    SPLIT_OPERATOR_DEFINITION,
    JOIN_OPERATOR_DEFINITION,
    TRIM_OPERATOR_DEFINITION,
    LOWERCASE_OPERATOR_DEFINITION,
    UPPERCASE_OPERATOR_DEFINITION,
    SLUGIFY_OPERATOR_DEFINITION,
    CONCAT_OPERATOR_DEFINITION,
    REPLACE_OPERATOR_DEFINITION,
    EXTRACT_REGEX_OPERATOR_DEFINITION,
    REPLACE_REGEX_OPERATOR_DEFINITION,
    STRIP_HTML_OPERATOR_DEFINITION,
    TRUNCATE_OPERATOR_DEFINITION,
];
