name: Feature Request
description: Suggest a new feature for the Data Hub plugin
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is this related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Extractors
        - Loaders
        - Transforms
        - Feeds
        - Pipeline execution
        - Dashboard UI
        - API/GraphQL
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
