import type { StepConfigSchema } from '../../../src/sdk/types/schema-types';
import { PIMCORE_EXTRACTOR_LIMITS } from '../constants';

export const PIMCORE_GRAPHQL_EXTRACTOR_SCHEMA: StepConfigSchema = {
    fields: [
        {
            key: 'connectionCode',
            label: 'GraphQL connection',
            type: 'connection',
            required: true,
            placeholder: 'pimcore-graphql',
            description: 'Saved HTTP, REST, or GraphQL connection containing the endpoint, headers, and authentication.',
            group: 'connection',
        },
        {
            key: 'timeoutMs',
            label: 'Request timeout (ms)',
            type: 'number',
            defaultValue: PIMCORE_EXTRACTOR_LIMITS.DEFAULT_TIMEOUT_MS,
            validation: { min: 1, max: PIMCORE_EXTRACTOR_LIMITS.MAX_TIMEOUT_MS },
            group: 'connection',
        },
        {
            key: 'entityType',
            label: 'Entity type',
            type: 'select',
            required: true,
            options: [
                { value: 'product', label: 'Product' },
                { value: 'category', label: 'Category' },
                { value: 'asset', label: 'Asset' },
            ],
            group: 'query',
        },
        {
            key: 'first',
            label: 'Page size',
            type: 'number',
            defaultValue: PIMCORE_EXTRACTOR_LIMITS.DEFAULT_PAGE_SIZE,
            validation: { min: 1, max: PIMCORE_EXTRACTOR_LIMITS.MAX_PAGE_SIZE },
            group: 'pagination',
        },
        {
            key: 'maxPages',
            label: 'Maximum pages',
            type: 'number',
            defaultValue: PIMCORE_EXTRACTOR_LIMITS.DEFAULT_MAX_PAGES,
            validation: { min: 1, max: PIMCORE_EXTRACTOR_LIMITS.MAX_PAGES },
            group: 'pagination',
        },
        {
            key: 'after',
            label: 'Initial offset',
            type: 'number',
            validation: { min: 0 },
            group: 'pagination',
        },
        { key: 'filter', label: 'Filter', type: 'json', group: 'query' },
        { key: 'sortBy', label: 'Sort field', type: 'string', group: 'query' },
        {
            key: 'sortOrder',
            label: 'Sort order',
            type: 'select',
            defaultValue: 'ASC',
            options: [
                { value: 'ASC', label: 'Ascending' },
                { value: 'DESC', label: 'Descending' },
            ],
            group: 'query',
        },
        { key: 'defaultLanguage', label: 'Default language', type: 'string', group: 'query' },
        {
            key: 'includeUnpublished',
            label: 'Include unpublished records returned by Pimcore',
            type: 'boolean',
            defaultValue: false,
            group: 'query',
        },
        { key: 'query', label: 'Custom GraphQL query', type: 'string', group: 'advanced' },
        { key: 'responseField', label: 'Listing response field', type: 'string', group: 'advanced' },
        { key: 'variables', label: 'Custom variables', type: 'json', group: 'advanced' },
        { key: 'assetUrlField', label: 'Asset URL field', type: 'string', group: 'advanced' },
        {
            key: 'maxRetries',
            label: 'Maximum attempts',
            type: 'number',
            defaultValue: PIMCORE_EXTRACTOR_LIMITS.DEFAULT_MAX_RETRIES,
            validation: { min: 1, max: PIMCORE_EXTRACTOR_LIMITS.MAX_RETRIES },
            group: 'advanced',
        },
        {
            key: 'retryDelayMs',
            label: 'Initial retry delay (ms)',
            type: 'number',
            defaultValue: PIMCORE_EXTRACTOR_LIMITS.DEFAULT_RETRY_DELAY_MS,
            validation: { min: 0, max: PIMCORE_EXTRACTOR_LIMITS.MAX_RETRY_DELAY_MS },
            group: 'advanced',
        },
    ],
    groups: [
        { id: 'connection', label: 'Connection' },
        { id: 'query', label: 'Query' },
        { id: 'pagination', label: 'Pagination' },
        { id: 'advanced', label: 'Advanced', collapsed: true },
    ],
};
