import { VendureEntityType } from "../../../../constants/enums";
import {
    ADDRESSES_MODE_OPTIONS,
    BOOLEAN_SELECT_OPTIONS,
    CONFLICT_RESOLUTION_OPTIONS,
    FACET_VALUES_MODE_OPTIONS,
    GROUPS_MODE_OPTIONS,
    LINES_MODE_OPTIONS,
    LOAD_STRATEGY_OPTIONS,
    ASSETS_MODE_OPTIONS,
    FEATURED_ASSET_MODE_OPTIONS,
} from "../../../../constants/adapter-schema-options";
import { LoaderDefinitionEntry, SKIP_DUPLICATES_FIELD, toEntityCode } from "./loader-registry.shared";

export const CORE_LOADER_DEFINITIONS: LoaderDefinitionEntry[] = [
    ['productUpsert', {
        definition: {
            type: 'LOADER',
            code: 'productUpsert',
            description: 'Upsert Products and default Variants by slug/SKU. Supports channel, multi-currency prices, tax category, stock and inventory flags.',
            requires: ['UpdateCatalog'],
            icon: 'box',
            color: '#6366f1',
            entityType: toEntityCode(VendureEntityType.PRODUCT),
            patchableFields: ['slug', 'name', 'description', 'sku', 'price', 'priceByCurrency', 'stockOnHand', 'trackInventory', 'enabled', 'customFields'],
            schema: {
                fields: [
                    { key: 'channel', label: 'Channel code', type: 'string', required: true },
                    { key: 'strategy', label: 'Load strategy', type: 'select', required: true, options: LOAD_STRATEGY_OPTIONS },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'conflictStrategy', label: 'Conflict strategy', type: 'select', required: true, options: CONFLICT_RESOLUTION_OPTIONS },
                    { key: 'nameField', label: 'Name field (from record)', type: 'string' },
                    { key: 'slugField', label: 'Slug field (from record)', type: 'string' },
                    { key: 'descriptionField', label: 'Description field (from record)', type: 'string' },
                    { key: 'enabledField', label: 'Enabled field (from record)', type: 'string', description: 'Record field containing product enabled/published flag (defaults to "enabled")' },
                    { key: 'skuField', label: 'SKU field (from record)', type: 'string' },
                    { key: 'priceField', label: 'Major-unit price field (from record)', type: 'string', description: 'Converted once to Vendure minor units using the configured MoneyStrategy precision' },
                    { key: 'priceByCurrencyField', label: 'Major-unit price map field (object)', type: 'string', description: 'Record field containing currency prices such as { USD: 19.99, EUR: 17.50 }' },
                    { key: 'taxCategoryName', label: 'Tax category name', type: 'string' },
                    { key: 'trackInventory', label: 'Track inventory', type: 'select', options: BOOLEAN_SELECT_OPTIONS },
                    { key: 'stockField', label: 'Stock on hand field', type: 'string' },
                    { key: 'stockByLocationField', label: 'Stock by location field (object)', type: 'string' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                    { key: 'createVariants', label: 'Create variants', type: 'boolean', description: 'Create/update a default variant alongside the product. Set to false when variants are handled by a separate variantUpsert step.' },
                    { key: 'channelsField', label: 'Channels field (array/string)', type: 'string', description: 'Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)' },
                    { key: 'translationsField', label: 'Translations field', type: 'string', description: 'Record field containing multi-language translations (array or object map). Overrides name/slug/description fields.' },
                    { key: 'facetValuesField', label: 'Facet values field (array)', type: 'string', description: 'Record field containing facet value codes or objects with a code property. Defaults to facetValueCodes.' },
                    { key: 'facetValuesMode', label: 'Facet values mode', type: 'select', options: FACET_VALUES_MODE_OPTIONS, description: 'Replace, merge, remove, or preserve product facet assignments when the facet values field is present.' },
                    { key: 'assetsField', label: 'Asset URLs field', type: 'string', description: 'Record field containing an array of asset URLs. Defaults to assetUrls.' },
                    { key: 'assetsMode', label: 'Assets mode', type: 'select', options: ASSETS_MODE_OPTIONS },
                    { key: 'featuredAssetField', label: 'Featured asset URL field', type: 'string', description: 'Record field containing the featured asset URL. Defaults to featuredAssetUrl.' },
                    { key: 'featuredAssetMode', label: 'Featured asset mode', type: 'select', options: FEATURED_ASSET_MODE_OPTIONS },
                ],
            },
        },
    }],
    ['variantUpsert', {
        definition: {
            type: 'LOADER',
            code: 'variantUpsert',
            description: 'Upsert ProductVariant by SKU. Supports create/update/upsert strategy, channel, prices, stock, tax, option groups, and custom fields. For creation, record must contain productSlug, productId, or productName to resolve the parent product.',
            requires: ['UpdateCatalog'],
            icon: 'package',
            color: '#14b8a6',
            entityType: toEntityCode(VendureEntityType.PRODUCT_VARIANT),
            patchableFields: ['sku', 'name', 'price', 'priceByCurrency', 'stockOnHand', 'optionGroups', 'optionIds', 'optionCodes', 'enabled', 'customFields'],
            schema: {
                fields: [
                    { key: 'channel', label: 'Channel code', type: 'string' },
                    { key: 'strategy', label: 'Load strategy', type: 'select', required: true, options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'skuField', label: 'SKU field (from record)', type: 'string', required: true },
                    { key: 'nameField', label: 'Name field (from record)', type: 'string' },
                    { key: 'priceField', label: 'Major-unit price field (from record)', type: 'string', description: 'Converted once to Vendure minor units using the configured MoneyStrategy precision' },
                    { key: 'priceByCurrencyField', label: 'Major-unit price map field (object)', type: 'string', description: 'Record field containing currency prices such as { USD: 19.99, EUR: 17.50 }' },
                    { key: 'taxCategoryName', label: 'Tax category name', type: 'string' },
                    { key: 'stockField', label: 'Stock on hand field', type: 'string' },
                    { key: 'stockByLocationField', label: 'Stock by location field (object)', type: 'string' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                    { key: 'optionGroupsField', label: 'Option groups field (object)', type: 'string', description: 'Record field containing option group→value pairs (e.g. { size: "S", color: "Blue" }). Auto-creates option groups and assigns to product.' },
                    { key: 'optionIdsField', label: 'Option IDs field (array)', type: 'string', description: 'Record field containing pre-existing Vendure option IDs (e.g. [1, 2, 3]). Passed directly without lookup.' },
                    { key: 'optionCodesField', label: 'Option codes field (array)', type: 'string', description: 'Record field containing option codes (e.g. ["size-s", "color-blue"]). Resolved to IDs by code lookup.' },
                    { key: 'enabledField', label: 'Enabled field (from record)', type: 'string', description: 'Record field containing variant enabled/published flag (defaults to "enabled")' },
                    { key: 'channelsField', label: 'Channels field (array/string)', type: 'string', description: 'Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)' },
                    { key: 'translationsField', label: 'Translations field', type: 'string', description: 'Record field containing multi-language translations (array or object map). Overrides name field.' },
                    { key: 'assetsField', label: 'Asset URLs field', type: 'string', description: 'Record field containing an array of asset URLs. Defaults to assetUrls.' },
                    { key: 'assetsMode', label: 'Assets mode', type: 'select', options: ASSETS_MODE_OPTIONS },
                    { key: 'featuredAssetField', label: 'Featured asset URL field', type: 'string', description: 'Record field containing the featured asset URL. Defaults to featuredAssetUrl.' },
                    { key: 'featuredAssetMode', label: 'Featured asset mode', type: 'select', options: FEATURED_ASSET_MODE_OPTIONS },
                ],
            },
        },
    }],
    ['customerUpsert', {
        definition: {
            type: 'LOADER',
            code: 'customerUpsert',
            description: 'Upsert Customer by email or externalId; merge addresses; assign groups.',
            requires: ['UpdateCustomer'],
            icon: 'users',
            color: '#10b981',
            entityType: toEntityCode(VendureEntityType.CUSTOMER),
            patchableFields: ['email', 'firstName', 'lastName', 'phoneNumber', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'emailField', label: 'Email field', type: 'string', required: true },
                    { key: 'firstNameField', label: 'First name field', type: 'string' },
                    { key: 'lastNameField', label: 'Last name field', type: 'string' },
                    { key: 'phoneNumberField', label: 'Phone number field', type: 'string' },
                    { key: 'addressesField', label: 'Addresses array field', type: 'string' },
                    { key: 'addressesMode', label: 'Addresses mode', type: 'select', options: ADDRESSES_MODE_OPTIONS, description: 'How to handle customer addresses on update (UPSERT_BY_MATCH prevents duplicates)' },
                    { key: 'addressMatchFields', label: 'Address match fields', type: 'string', defaultValue: 'streetLine1,city,countryCode', description: 'Comma-separated fields to match existing addresses (for UPSERT_BY_MATCH mode)' },
                    { key: 'groupsField', label: 'Group names array field', type: 'string' },
                    { key: 'groupsMode', label: 'Groups mode', type: 'select', options: GROUPS_MODE_OPTIONS },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                ],
            },
        },
    }],
    ['orderUpsert', {
        definition: {
            type: 'LOADER',
            code: 'orderUpsert',
            description: 'Upsert Order by code for system migrations. Creates order with customer, line items, addresses, and state transitions.',
            requires: ['UpdateOrder'],
            icon: 'shopping-cart',
            color: '#f97316',
            entityType: toEntityCode(VendureEntityType.ORDER),
            patchableFields: ['code', 'customerEmail', 'lines', 'shippingAddress', 'billingAddress', 'shippingMethodCode', 'paymentMethodCode', 'state', 'orderPlacedAt', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'lookupFields', label: 'Lookup fields', type: 'string', description: 'Comma-separated fields for existing entity lookup (default: code)' },
                    { key: 'codeField', label: 'Order code field', type: 'string', description: 'Record field for order code (default: code)' },
                    { key: 'customerEmailField', label: 'Customer email field', type: 'string', description: 'Record field for customer email (default: customerEmail)' },
                    { key: 'linesField', label: 'Lines field', type: 'string', description: 'Record field for order lines array (default: lines)' },
                    { key: 'linesMode', label: 'Lines mode', type: 'select', options: LINES_MODE_OPTIONS, description: 'How to handle order lines on update' },
                    { key: 'linesMatchBy', label: 'Lines match by', type: 'string', defaultValue: 'sku', description: 'Field to match order lines by (for MERGE_BY_SKU and UPDATE_BY_ID modes)' },
                    { key: 'shippingAddressField', label: 'Shipping address field', type: 'string' },
                    { key: 'billingAddressField', label: 'Billing address field', type: 'string' },
                    { key: 'shippingMethodCodeField', label: 'Shipping method code field', type: 'string' },
                    { key: 'paymentMethodCode', label: 'Payment method code', type: 'string', description: 'Payment method code for state transitions (auto-resolved if not set)' },
                    { key: 'paymentMethodCodeField', label: 'Payment method code field', type: 'string', description: 'Record field for dynamic payment method code' },
                    { key: 'state', label: 'Target state', type: 'string', description: 'State to transition order to after creation (e.g. ArrangingPayment, PaymentSettled)' },
                    { key: 'stateField', label: 'State field', type: 'string', description: 'Record field for dynamic state (default: state)' },
                    { key: 'orderPlacedAtField', label: 'Order placed at field', type: 'string', description: 'Record field for backdated order date' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string' },
                ],
            },
        },
    }],
    ['orderNote', {
        definition: {
            type: 'LOADER',
            code: 'orderNote',
            description: 'Attach a note to an Order by code or id.',
            requires: ['UpdateOrder'],
            icon: 'shopping-cart',
            color: '#f97316',
            entityType: toEntityCode(VendureEntityType.ORDER),
            patchableFields: ['orderId', 'orderCode', 'note', 'isPrivate'],
            schema: {
                fields: [
                    { key: 'orderCodeField', label: 'Order code field', type: 'string' },
                    { key: 'orderIdField', label: 'Order id field', type: 'string' },
                    { key: 'noteField', label: 'Note text field', type: 'string', required: true },
                    { key: 'isPrivate', label: 'Private note', type: 'boolean' },
                ],
            },
        },
    }],
    ['stockAdjust', {
        definition: {
            type: 'LOADER',
            code: 'stockAdjust',
            description: 'Set or adjust stock levels by SKU and exact stock location name.',
            requires: ['UpdateCatalog'],
            icon: 'layers',
            color: '#0ea5e9',
            entityType: toEntityCode(VendureEntityType.INVENTORY),
            patchableFields: ['sku', 'stockByLocation'],
            schema: {
                fields: [
                    { key: 'skuField', label: 'SKU field', type: 'string', required: true },
                    { key: 'stockByLocationField', label: 'Stock by location map (name → quantity)', type: 'string', required: true },
                    { key: 'absolute', label: 'Set absolute values', type: 'boolean', defaultValue: true, description: 'Disable to apply each quantity as a delta.' },
                ],
            },
        },
    }],
    ['applyCoupon', {
        definition: {
            type: 'LOADER',
            code: 'applyCoupon',
            description: 'Apply a coupon code to an Order by id/code.',
            requires: ['UpdateOrder'],
            icon: 'shopping-cart',
            color: '#f97316',
            entityType: toEntityCode(VendureEntityType.ORDER),
            patchableFields: ['orderId', 'orderCode', 'coupon'],
            schema: {
                fields: [
                    { key: 'orderIdField', label: 'Order id field', type: 'string' },
                    { key: 'orderCodeField', label: 'Order code field', type: 'string' },
                    { key: 'couponField', label: 'Coupon code field', type: 'string', required: true },
                ],
            },
        },
    }],
];
