import { VendureEntityType } from "../../../../constants/enums";
import {
    AUTH_TYPE_GRAPHQL_OPTIONS,
    AUTH_TYPE_REST_OPTIONS,
    BATCH_MODE_GRAPHQL_OPTIONS,
    BATCH_MODE_REST_OPTIONS,
    HTTP_METHOD_WRITE_OPTIONS,
    LOAD_STRATEGY_OPTIONS,
} from "../../../../constants/adapter-schema-options";
import { LoaderDefinitionEntry, SKIP_DUPLICATES_FIELD, toEntityCode } from "./loader-registry.shared";
import { FIELD_LIMITS } from '../../../../constants/validation';
import { HTTP } from '../../../../../shared/constants';

const HTTP_LOADER_DELIVERY_FIELDS = [
    {
        key: 'maxBatchSize',
        label: 'Maximum batch size',
        type: 'number',
        defaultValue: 0,
        validation: { min: 0, max: FIELD_LIMITS.BATCH_SIZE_MAX },
        description: `Records per batched request; 0 sends all records together (0-${FIELD_LIMITS.BATCH_SIZE_MAX}).`,
    },
    {
        key: 'retries',
        label: 'Retries',
        type: 'number',
        defaultValue: 0,
        validation: { min: 0, max: HTTP.MAX_RETRY_ATTEMPTS },
        description: `Retries after the first attempt (0-${HTTP.MAX_RETRY_ATTEMPTS}).`,
    },
    {
        key: 'retryDelayMs',
        label: 'Initial retry delay (ms)',
        type: 'number',
        defaultValue: 0,
        validation: { min: 0, max: HTTP.MAX_TIMEOUT_MS },
    },
    {
        key: 'maxRetryDelayMs',
        label: 'Maximum retry delay (ms)',
        type: 'number',
        defaultValue: HTTP.RETRY_MAX_DELAY_MS,
        validation: { min: 0, max: HTTP.MAX_TIMEOUT_MS },
    },
    {
        key: 'backoffMultiplier',
        label: 'Backoff multiplier',
        type: 'number',
        defaultValue: HTTP.BACKOFF_MULTIPLIER,
        validation: { min: 1, max: HTTP.MAX_BACKOFF_MULTIPLIER },
    },
    {
        key: 'timeoutMs',
        label: 'Timeout (ms)',
        type: 'number',
        defaultValue: HTTP.TIMEOUT_MS,
        validation: { min: 1, max: HTTP.MAX_TIMEOUT_MS },
    },
] as const;

export const INTEGRATION_LOADER_DEFINITIONS: LoaderDefinitionEntry[] = [
    ['restPost', {
        definition: {
            type: 'LOADER',
            code: 'restPost',
            description: 'POST/PUT records to an external REST endpoint. Supports auth and per-record POST or array batch.',
            requires: ['UpdateDataHubSettings'],
            icon: 'globe',
            color: '#8b5cf6',
            patchableFields: ['*'],
            schema: {
                fields: [
                    { key: 'endpoint', label: 'Endpoint', type: 'string', required: true },
                    { key: 'method', label: 'Method', type: 'select', required: true, options: HTTP_METHOD_WRITE_OPTIONS },
                    { key: 'headers', label: 'Headers (JSON)', type: 'json' },
                    { key: 'auth', label: 'Auth preset', type: 'select', options: AUTH_TYPE_REST_OPTIONS },
                    { key: 'bearerTokenSecretCode', label: 'Bearer token secret code', type: 'secret' },
                    { key: 'basicSecretCode', label: 'Basic auth secret code', type: 'secret' },
                    { key: 'hmacSecretCode', label: 'HMAC secret code', type: 'secret' },
                    { key: 'hmacHeader', label: 'HMAC header name', type: 'string' },
                    { key: 'hmacPayloadTemplate', label: 'HMAC payload template', type: 'string', description: 'e.g. ${method}:${path}:${timestamp}' },
                    { key: 'batchMode', label: 'Batch mode', type: 'select', options: BATCH_MODE_REST_OPTIONS },
                    ...HTTP_LOADER_DELIVERY_FIELDS,
                ],
            },
        },
    }],
    ['graphqlMutation', {
        definition: {
            type: 'LOADER',
            code: 'graphqlMutation',
            description: 'Send records as GraphQL mutations to an external API endpoint. Supports variable mapping, auth, batching, and retries.',
            requires: ['UpdateDataHubSettings'],
            icon: 'code',
            color: '#e11d48',
            patchableFields: ['*'],
            schema: {
                fields: [
                    { key: 'endpoint', label: 'Endpoint URL', type: 'string', required: true },
                    { key: 'mutation', label: 'GraphQL mutation', type: 'code', required: true, description: 'The GraphQL mutation string (e.g. mutation CreateProduct($input: ProductInput!) { createProduct(input: $input) { id } })' },
                    { key: 'variableMapping', label: 'Variable mapping (JSON)', type: 'json', required: true, description: 'Maps GraphQL variable paths to record field paths (e.g. {"input.name": "productName", "input.sku": "sku"})' },
                    { key: 'headers', label: 'Headers (JSON)', type: 'json' },
                    { key: 'auth', label: 'Auth preset', type: 'select', options: AUTH_TYPE_GRAPHQL_OPTIONS },
                    { key: 'bearerTokenSecretCode', label: 'Bearer token secret code', type: 'secret' },
                    { key: 'basicSecretCode', label: 'Basic auth secret code', type: 'secret' },
                    { key: 'batchMode', label: 'Batch mode', type: 'select', options: BATCH_MODE_GRAPHQL_OPTIONS },
                    ...HTTP_LOADER_DELIVERY_FIELDS,
                ],
            },
        },
    }],
    ['taxRateUpsert', {
        definition: {
            type: 'LOADER',
            code: 'taxRateUpsert',
            description: 'Upsert TaxRate by name; resolves tax category and zone by code.',
            requires: ['UpdateSettings'],
            icon: 'settings',
            color: '#64748b',
            entityType: toEntityCode(VendureEntityType.TAX_RATE),
            patchableFields: ['name', 'value', 'enabled', 'taxCategoryCode', 'taxCategoryId', 'zoneCode', 'zoneId', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'nameField', label: 'Name field', type: 'string', required: true, description: 'Field containing tax rate name' },
                    { key: 'valueField', label: 'Value field', type: 'string', required: true, description: 'Field containing tax rate percentage (0-100)' },
                    { key: 'enabledField', label: 'Enabled field', type: 'string', description: 'Field indicating if rate is active' },
                    { key: 'taxCategoryCodeField', label: 'Tax category code field', type: 'string', description: 'Field containing TaxCategory customFields.code' },
                    { key: 'taxCategoryIdField', label: 'Tax category ID field', type: 'string', description: 'Alternative: field containing tax category ID' },
                    { key: 'zoneCodeField', label: 'Zone code field', type: 'string', description: 'Field containing Zone customFields.code' },
                    { key: 'zoneIdField', label: 'Zone ID field', type: 'string', description: 'Alternative: field containing zone ID' },
                ],
            },
        },
    }],
    ['paymentMethodUpsert', {
        definition: {
            type: 'LOADER',
            code: 'paymentMethodUpsert',
            description: 'Upsert PaymentMethod by code; configure handler and eligibility checker.',
            requires: ['UpdateSettings'],
            icon: 'settings',
            color: '#64748b',
            entityType: toEntityCode(VendureEntityType.PAYMENT_METHOD),
            patchableFields: ['name', 'code', 'description', 'enabled', 'handler', 'checker', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'nameField', label: 'Name field', type: 'string', required: true, description: 'Field containing payment method name' },
                    { key: 'codeField', label: 'Code field', type: 'string', required: true, description: 'Field containing unique payment method code' },
                    { key: 'descriptionField', label: 'Description field', type: 'string', description: 'Field containing description shown to customers' },
                    { key: 'enabledField', label: 'Enabled field', type: 'string', description: 'Field indicating if method is active' },
                    { key: 'handlerField', label: 'Handler field', type: 'string', required: true, description: 'Field containing handler config { code, args }' },
                    { key: 'checkerField', label: 'Checker field', type: 'string', description: 'Field containing eligibility checker config { code, args }' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                    { key: 'translationsField', label: 'Translations field', type: 'string', description: 'Record field containing multi-language translations (array or object map). Overrides name/description fields.' },
                    { key: 'channelsField', label: 'Channels field (array/string)', type: 'string', description: 'Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)' },
                ],
            },
        },
    }],
    ['channelUpsert', {
        definition: {
            type: 'LOADER',
            code: 'channelUpsert',
            description: 'Upsert Channel by code; configure currencies, languages, and zones.',
            requires: ['UpdateSettings'],
            icon: 'settings',
            color: '#64748b',
            entityType: toEntityCode(VendureEntityType.CHANNEL),
            patchableFields: ['code', 'token', 'defaultLanguageCode', 'defaultCurrencyCode', 'pricesIncludeTax', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'codeField', label: 'Code field', type: 'string', required: true, description: 'Field containing unique channel code' },
                    { key: 'tokenField', label: 'Token field', type: 'string', description: 'Field containing channel token (auto-generated if not provided)' },
                    { key: 'defaultLanguageCodeField', label: 'Default language code field', type: 'string', required: true, description: 'Field containing default language (e.g., "en")' },
                    { key: 'availableLanguageCodesField', label: 'Available languages field', type: 'string', description: 'Field containing array of language codes' },
                    { key: 'defaultCurrencyCodeField', label: 'Default currency code field', type: 'string', required: true, description: 'Field containing default currency (e.g., "USD")' },
                    { key: 'availableCurrencyCodesField', label: 'Available currencies field', type: 'string', description: 'Field containing array of currency codes' },
                    { key: 'pricesIncludeTaxField', label: 'Prices include tax field', type: 'string', description: 'Field indicating if prices include tax' },
                    { key: 'defaultTaxZoneCodeField', label: 'Default tax zone code field', type: 'string', description: 'Field containing default tax zone code' },
                    { key: 'defaultShippingZoneCodeField', label: 'Default shipping zone code field', type: 'string', description: 'Field containing default shipping zone code' },
                    { key: 'sellerIdField', label: 'Seller ID field', type: 'string', description: 'Field containing seller ID (for multi-vendor)' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                ],
            },
        },
    }],
    ['shippingMethodUpsert', {
        definition: {
            type: 'LOADER',
            code: 'shippingMethodUpsert',
            description: 'Upsert ShippingMethod by code; configure calculator, checker, and fulfillment handler. Supports multi-language translations and multi-channel assignment.',
            requires: ['UpdateShippingMethod'],
            icon: 'settings',
            color: '#64748b',
            entityType: toEntityCode(VendureEntityType.SHIPPING_METHOD),
            patchableFields: ['name', 'code', 'description', 'fulfillmentHandler', 'calculator', 'checker', 'customFields'],
            schema: {
                fields: [
                    { key: 'strategy', label: 'Load strategy', type: 'select', options: LOAD_STRATEGY_OPTIONS, description: 'UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.' },
                    SKIP_DUPLICATES_FIELD,
                    { key: 'nameField', label: 'Name field', type: 'string', required: true, description: 'Field containing shipping method display name' },
                    { key: 'codeField', label: 'Code field', type: 'string', required: true, description: 'Field containing unique shipping method code' },
                    { key: 'descriptionField', label: 'Description field', type: 'string', description: 'Field containing description shown to customers' },
                    { key: 'fulfillmentHandlerField', label: 'Fulfillment handler field', type: 'string', required: true, description: 'Field containing fulfillment handler code (e.g., "manual-fulfillment")' },
                    { key: 'calculatorField', label: 'Calculator field', type: 'string', required: true, description: 'Field containing calculator config { code, args }' },
                    { key: 'checkerField', label: 'Checker field', type: 'string', description: 'Field containing eligibility checker config { code, args }' },
                    { key: 'customFieldsField', label: 'Custom fields field (object)', type: 'string', description: 'Record field containing custom field values (defaults to "customFields")' },
                    { key: 'translationsField', label: 'Translations field', type: 'string', description: 'Record field containing multi-language translations (array or object map). Overrides name/description fields.' },
                    { key: 'channelsField', label: 'Channels field (array/string)', type: 'string', description: 'Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)' },
                ],
            },
        },
    }],
];
