import { StepConfigSchema } from '../../types/index';
import { FileFormat } from '../../constants/enums';
import { S3_DEFAULTS } from './types';
import { FILE_FORMAT_OPTIONS, CSV_DELIMITER_OPTIONS, S3_SELECT_FORMAT_OPTIONS } from '../../constants/adapter-schema-options';

export const S3_EXTRACTOR_SCHEMA: StepConfigSchema = {
    groups: [
        { id: 'connection', label: 'Connection', description: 'S3 connection settings' },
        { id: 'source', label: 'Source', description: 'Bucket and object settings' },
        { id: 'format', label: 'Format', description: 'File format options' },
        { id: 's3select', label: 'S3 Select', description: 'Server-side filtering' },
        { id: 'postProcess', label: 'Post-Processing', description: 'Actions after processing' },
        { id: 'advanced', label: 'Advanced', description: 'Advanced options' },
    ],
    fields: [
        // Connection
        {
            key: 'connectionCode',
            label: 'Connection',
            description: 'Use a saved S3 connection',
            type: 'connection',
            group: 'connection',
        },
        {
            key: 'region',
            label: 'Region',
            description: 'AWS region (e.g., us-east-1)',
            type: 'string',
            placeholder: 'us-east-1',
            group: 'connection',
        },
        {
            key: 'endpoint',
            label: 'Custom Endpoint',
            description: 'Custom S3 endpoint URL (for MinIO, DigitalOcean Spaces, etc.)',
            type: 'string',
            placeholder: 'https://s3.example.com',
            group: 'connection',
        },
        {
            key: 'accessKeyIdSecretCode',
            label: 'Access Key ID',
            description: 'Secret code for AWS Access Key ID',
            type: 'secret',
            group: 'connection',
        },
        {
            key: 'secretAccessKeySecretCode',
            label: 'Secret Access Key',
            description: 'Secret code for AWS Secret Access Key',
            type: 'secret',
            group: 'connection',
        },
        {
            key: 'forcePathStyle',
            label: 'Force Path Style',
            description: 'Use path-style addressing (required for some S3-compatible services)',
            type: 'boolean',
            defaultValue: false,
            group: 'connection',
        },
        // Source
        {
            key: 'bucket',
            label: 'Bucket',
            description: 'S3 bucket name',
            type: 'string',
            required: true,
            placeholder: 'my-data-bucket',
            group: 'source',
        },
        {
            key: 'prefix',
            label: 'Prefix',
            description: 'Object key prefix (folder path)',
            type: 'string',
            placeholder: 'data/imports/',
            group: 'source',
        },
        {
            key: 'suffix',
            label: 'Suffix',
            description: 'Object key suffix (e.g., .csv, .json)',
            type: 'string',
            placeholder: '.csv',
            group: 'source',
        },
        // Format
        {
            key: 'format',
            label: 'File Format',
            type: 'select',
            options: FILE_FORMAT_OPTIONS,
            group: 'format',
        },
        {
            key: 'csv.delimiter',
            label: 'CSV Delimiter',
            type: 'select',
            options: CSV_DELIMITER_OPTIONS,
            defaultValue: ',',
            group: 'format',
            dependsOn: { field: 'format', value: FileFormat.CSV },
        },
        {
            key: 'csv.header',
            label: 'Has Header Row',
            type: 'boolean',
            defaultValue: true,
            group: 'format',
            dependsOn: { field: 'format', value: FileFormat.CSV },
        },
        {
            key: 'json.path',
            label: 'JSON Data Path',
            description: 'Path to records array in JSON',
            type: 'string',
            placeholder: 'data.items',
            group: 'format',
            dependsOn: { field: 'format', value: FileFormat.JSON },
        },
        // S3 Select
        {
            key: 's3Select.enabled',
            label: 'Use S3 Select',
            description: 'Use S3 Select for server-side filtering (CSV/JSON only)',
            type: 'boolean',
            defaultValue: false,
            group: 's3select',
        },
        {
            key: 's3Select.expression',
            label: 'SQL Expression',
            description: 'S3 Select SQL expression',
            type: 'string',
            placeholder: "SELECT * FROM s3object WHERE status = 'active'",
            group: 's3select',
            dependsOn: { field: 's3Select.enabled', value: true },
        },
        {
            key: 's3Select.inputSerialization',
            label: 'Input Format',
            type: 'select',
            options: S3_SELECT_FORMAT_OPTIONS,
            defaultValue: FileFormat.CSV,
            group: 's3select',
            dependsOn: { field: 's3Select.enabled', value: true },
        },
        // Post-Processing
        {
            key: 'deleteAfterProcess',
            label: 'Delete After Processing',
            description: 'Delete objects after successful processing',
            type: 'boolean',
            defaultValue: false,
            group: 'postProcess',
        },
        {
            key: 'moveAfterProcess.enabled',
            label: 'Move After Processing',
            description: 'Move objects to another prefix after processing',
            type: 'boolean',
            defaultValue: false,
            group: 'postProcess',
        },
        {
            key: 'moveAfterProcess.destinationPrefix',
            label: 'Destination Prefix',
            description: 'Prefix to move processed objects to',
            type: 'string',
            placeholder: 'data/processed/',
            group: 'postProcess',
            dependsOn: { field: 'moveAfterProcess.enabled', value: true },
        },
        // Advanced
        {
            key: 'modifiedAfter',
            label: 'Modified After',
            description: 'Only process objects modified after this date',
            type: 'string',
            placeholder: '2024-01-01T00:00:00Z',
            group: 'advanced',
        },
        {
            key: 'maxObjects',
            label: 'Max Objects',
            description: 'Maximum number of objects to process',
            type: 'number',
            defaultValue: S3_DEFAULTS.maxObjects,
            group: 'advanced',
        },
        {
            key: 'includeObjectMetadata',
            label: 'Include Object Metadata',
            description: 'Add S3 metadata (key, size, etag) to records',
            type: 'boolean',
            defaultValue: false,
            group: 'advanced',
        },
        {
            key: 'continueOnError',
            label: 'Continue on Error',
            type: 'boolean',
            defaultValue: true,
            group: 'advanced',
        },
    ],
};
