export const SCHEMA_REGISTRY = {
    MAX_SCHEMA_ID_LENGTH: 255,
    MAX_VERSION_LENGTH: 100,
    MAX_DEFINITION_BYTES: 1_048_576,
    MAX_METADATA_BYTES: 65_536,
    MAX_METADATA_DEPTH: 16,
    MAX_RECORDS_PER_VALIDATION_BATCH: 10_000,
    MAX_VERSIONS_PER_SCHEMA: 1_000,
    MAX_DEFINITION_DEPTH: 32,
    MAX_VALIDATION_ISSUES_PER_RECORD: 100,
    MAX_PIPELINE_DISCOVERY: 10_000,
} as const;
