/**
 * Auto-generated Loader Configuration Types
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate-loader-types.ts
 * Generated at: 2026-02-28T16:38:27.739Z
 *
 * This file provides TypeScript interfaces for all loader configurations,
 * enabling IDE auto-complete and compile-time validation.
 *
 * Usage:
 * ```typescript
 * import type { ProductUpsertConfig, LoaderConfig } from "./types/loader-configs";
 *
 * const config: ProductUpsertConfig = {
 *   adapterCode: "productUpsert",
 *   nameField: "name",  // ← IDE auto-complete available!
 *   slugField: "slug",
 * };
 * ```
 */

// ============================================================================
// INDIVIDUAL LOADER CONFIGURATIONS
// ============================================================================

/**
 * Upsert Products and default Variants by slug/SKU. Supports channel, multi-currency prices, tax category, stock and inventory flags.
 * @requires UpdateCatalog
 * @entityType product
 */
export interface ProductUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'productUpsert';
    /** Channel code */
    channel: string;
    /** Load strategy */
    strategy: string;
    /** Conflict strategy */
    conflictStrategy: string;
    /** Name field (from record) */
    nameField?: string;
    /** Slug field (from record) */
    slugField?: string;
    /** Description field (from record) */
    descriptionField?: string;
    /**
     * Enabled field (from record)
     * Record field containing product enabled/published flag (defaults to "enabled")
     */
    enabledField?: string;
    /** SKU field (from record) */
    skuField?: string;
    /** Price field (from record) */
    priceField?: string;
    /** Tax category name */
    taxCategoryName?: string;
    /** Track inventory */
    trackInventory?: string;
    /** Stock on hand field */
    stockField?: string;
    /** Stock by location field (object) */
    stockByLocationField?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Create variants
     * Create/update a default variant alongside the product. Set to false when variants are handled by a separate variantUpsert step.
     */
    createVariants?: boolean;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name/slug/description fields.
     */
    translationsField?: string;
    /**
     * Facet values mode
     * How to handle product facet values on update
     */
    facetValuesMode?: string;
    /**
     * Assets mode
     * How to handle product assets on update
     */
    assetsMode?: string;
    /**
     * Featured asset mode
     * How to handle product featured asset on update
     */
    featuredAssetMode?: string;
}

/**
 * Upsert ProductVariant by SKU. Supports create/update/upsert strategy, channel, prices, stock, tax, option groups, and custom fields. For creation, record must contain productSlug, productId, or productName to resolve the parent product.
 * @requires UpdateCatalog
 * @entityType product-variant
 */
export interface VariantUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'variantUpsert';
    /** Channel code */
    channel?: string;
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy: string;
    /** SKU field (from record) */
    skuField: string;
    /** Name field (from record) */
    nameField?: string;
    /** Price field (from record) */
    priceField?: string;
    /** Price map field (object) */
    priceByCurrencyField?: string;
    /** Tax category name */
    taxCategoryName?: string;
    /** Stock on hand field */
    stockField?: string;
    /** Stock by location field (object) */
    stockByLocationField?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /** Option groups field (object) */
    optionGroupsField?: string;
    /**
     * Option IDs field (array)
     * Record field containing pre-existing Vendure option IDs (e.g. [1, 2, 3]). Passed directly without lookup.
     */
    optionIdsField?: string;
    /**
     * Option codes field (array)
     * Record field containing option codes (e.g. ["size-s", "color-blue"]). Resolved to IDs by code lookup.
     */
    optionCodesField?: string;
    /**
     * Enabled field (from record)
     * Record field containing variant enabled/published flag (defaults to "enabled")
     */
    enabledField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name field.
     */
    translationsField?: string;
    /**
     * Facet values mode
     * How to handle variant facet values on update
     */
    facetValuesMode?: string;
    /**
     * Assets mode
     * How to handle variant assets on update
     */
    assetsMode?: string;
    /**
     * Featured asset mode
     * How to handle variant featured asset on update
     */
    featuredAssetMode?: string;
    /**
     * Options mode
     * How to handle variant options on update
     */
    optionsMode?: string;
}

/**
 * Upsert Customer by email or externalId; merge addresses; assign groups.
 * @requires UpdateCustomer
 * @entityType customer
 */
export interface CustomerUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'customerUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /** Email field */
    emailField: string;
    /** First name field */
    firstNameField?: string;
    /** Last name field */
    lastNameField?: string;
    /** Phone number field */
    phoneNumberField?: string;
    /** Addresses array field */
    addressesField?: string;
    /**
     * Addresses mode
     * How to handle customer addresses on update (UPSERT_BY_MATCH prevents duplicates)
     */
    addressesMode?: string;
    /**
     * Address match fields
     * Comma-separated fields to match existing addresses (for UPSERT_BY_MATCH mode)
     * @default streetLine1,city,countryCode
     */
    addressMatchFields?: string;
    /** Group codes array field */
    groupsField?: string;
    /** Groups mode */
    groupsMode?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
}

/**
 * Upsert Order by code for system migrations. Creates order with customer, line items, addresses, and state transitions.
 * @requires UpdateOrder
 * @entityType order
 */
export interface OrderUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'orderUpsert';
    /** Load strategy */
    strategy?: string;
    /**
     * Lookup fields
     * Comma-separated fields for existing entity lookup (default: code)
     */
    lookupFields?: string;
    /**
     * Order code field
     * Record field for order code (default: code)
     */
    codeField?: string;
    /**
     * Customer email field
     * Record field for customer email (default: customerEmail)
     */
    customerEmailField?: string;
    /**
     * Lines field
     * Record field for order lines array (default: lines)
     */
    linesField?: string;
    /**
     * Lines mode
     * How to handle order lines on update
     */
    linesMode?: string;
    /**
     * Lines match by
     * Field to match order lines by (for MERGE_BY_SKU and UPDATE_BY_ID modes)
     * @default sku
     */
    linesMatchBy?: string;
    /** Shipping address field */
    shippingAddressField?: string;
    /** Billing address field */
    billingAddressField?: string;
    /** Shipping method code field */
    shippingMethodCodeField?: string;
    /**
     * Payment method code
     * Payment method code for state transitions (auto-resolved if not set)
     */
    paymentMethodCode?: string;
    /**
     * Payment method code field
     * Record field for dynamic payment method code
     */
    paymentMethodCodeField?: string;
    /**
     * Target state
     * State to transition order to after creation (e.g. ArrangingPayment, PaymentSettled)
     */
    state?: string;
    /**
     * State field
     * Record field for dynamic state (default: state)
     */
    stateField?: string;
    /**
     * Order placed at field
     * Record field for backdated order date
     */
    orderPlacedAtField?: string;
    /** Custom fields field (object) */
    customFieldsField?: string;
}

/**
 * Attach a note to an Order by code or id.
 * @requires UpdateOrder
 * @entityType order
 */
export interface OrderNoteConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'orderNote';
    /** Order code field */
    orderCodeField?: string;
    /** Order id field */
    orderIdField?: string;
    /** Note text field */
    noteField: string;
    /** Private note */
    isPrivate?: boolean;
}

/**
 * Adjust stock levels by SKU and stock location code map.
 * @requires UpdateCatalog
 * @entityType inventory
 */
export interface StockAdjustConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'stockAdjust';
    /** SKU field */
    skuField: string;
    /** Stock by location map (code->qty) */
    stockByLocationField: string;
    /** Set absolute (else delta) */
    absolute?: boolean;
}

/**
 * Apply a coupon code to an Order by id/code.
 * @requires UpdateOrder
 * @entityType order
 */
export interface ApplyCouponConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'applyCoupon';
    /** Order id field */
    orderIdField?: string;
    /** Order code field */
    orderCodeField?: string;
    /** Coupon code field */
    couponField: string;
}

/**
 * Upsert Collection by slug/code; supports create/update/upsert strategy, channel, multi-language, multi-channel, and custom fields.
 * @requires UpdateCatalog
 * @entityType collection
 */
export interface CollectionUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'collectionUpsert';
    /** Channel code */
    channel?: string;
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /** Slug field */
    slugField: string;
    /** Name field */
    nameField: string;
    /** Parent slug field */
    parentSlugField?: string;
    /** Description field */
    descriptionField?: string;
    /** Apply filters job */
    applyFilters?: boolean;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name/slug/description fields.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
    /**
     * Private flag field
     * Record field containing isPrivate boolean flag
     */
    isPrivateField?: string;
    /**
     * Assets mode
     * How to handle collection assets on update
     */
    assetsMode?: string;
    /**
     * Filters mode
     * How to handle collection filters on update
     */
    filtersMode?: string;
}

/**
 * Upsert Promotion by couponCode; create/update enabled dates/actions/conditions. Supports custom fields.
 * @requires UpdatePromotion
 * @entityType promotion
 */
export interface PromotionUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'promotionUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /** Coupon code field */
    codeField: string;
    /** Name field */
    nameField?: string;
    /** Enabled field */
    enabledField?: string;
    /** Starts at field */
    startsAtField?: string;
    /** Ends at field */
    endsAtField?: string;
    /** Conditions field (JSON) */
    conditionsField?: string;
    /**
     * Conditions mode
     * How to handle promotion conditions on update
     */
    conditionsMode?: string;
    /** Actions field (JSON) */
    actionsField?: string;
    /**
     * Actions mode
     * How to handle promotion actions on update
     */
    actionsMode?: string;
    /** Channel code */
    channel?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Description field
     * Record field containing promotion description (defaults to "description")
     */
    descriptionField?: string;
    /**
     * Per-customer usage limit field
     * Record field containing the per-customer usage limit (integer)
     */
    perCustomerUsageLimitField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name/description fields.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
}

/**
 * Transition an order to a new state by id/code.
 * @requires UpdateOrder
 * @entityType order
 */
export interface OrderTransitionConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'orderTransition';
    /** Order id field */
    orderIdField?: string;
    /** Order code field */
    orderCodeField?: string;
    /** Target state */
    state: string;
}

/**
 * Attach existing Asset (by id) as featured asset to a Product/Collection by slug.
 * @requires UpdateCatalog
 * @entityType asset
 */
export interface AssetAttachConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'assetAttach';
    /** Entity type */
    entity: string;
    /** Slug field */
    slugField: string;
    /** Asset ID field */
    assetIdField: string;
    /** Channel code */
    channel?: string;
}

/**
 * Import Asset from URL. Downloads file and creates asset in Vendure.
 * @requires UpdateCatalog
 * @entityType asset
 */
export interface AssetImportConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'assetImport';
    /** Source URL field */
    sourceUrlField: string;
    /** Filename field */
    filenameField?: string;
    /** Name field */
    nameField?: string;
    /** Tags field (array) */
    tagsField?: string;
    /** Channel code */
    channel?: string;
}

/**
 * Upsert Facet by code; create or update facet. Supports custom fields.
 * @requires UpdateCatalog
 * @entityType facet
 */
export interface FacetUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'facetUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /** Code field */
    codeField: string;
    /** Name field */
    nameField: string;
    /** Private field */
    privateField?: string;
    /** Channel code */
    channel?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name field.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
}

/**
 * Upsert FacetValue by code; requires facet to exist. Supports custom fields.
 * @requires UpdateCatalog
 * @entityType facet-value
 */
export interface FacetValueUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'facetValueUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /** Facet code field */
    facetCodeField: string;
    /** Value code field */
    codeField: string;
    /** Value name field */
    nameField: string;
    /** Channel code */
    channel?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name field.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
}

/**
 * POST/PUT records to an external REST endpoint. Supports auth and per-record POST or array batch.
 * @requires UpdateDataHubSettings
 */
export interface RestPostConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'restPost';
    /** Endpoint */
    endpoint: string;
    /** Method */
    method: string;
    /** Headers (JSON) */
    headers?: Record<string, unknown>;
    /** Auth preset */
    auth?: string;
    /** Bearer token secret code */
    bearerTokenSecretCode?: string;
    /** Basic auth secret code */
    basicSecretCode?: string;
    /** HMAC secret code */
    hmacSecretCode?: string;
    /** HMAC header name */
    hmacHeader?: string;
    /** HMAC payload template */
    hmacPayloadTemplate?: string;
    /** Batch mode */
    batchMode?: string;
    /**
     * Max batch size (array mode)
     * Chunk size when batchMode=array
     */
    maxBatchSize?: number;
    /**
     * Retries
     * Number of retries for failed requests
     */
    retries?: number;
    /**
     * Retry delay (ms)
     * Delay between retries
     */
    retryDelayMs?: number;
    /**
     * Timeout (ms)
     * Request timeout in milliseconds
     */
    timeoutMs?: number;
}

/**
 * Send records as GraphQL mutations to an external API endpoint. Supports variable mapping, auth, batching, and retries.
 * @requires UpdateDataHubSettings
 */
export interface GraphqlMutationConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'graphqlMutation';
    /** Endpoint URL */
    endpoint: string;
    /** GraphQL mutation */
    mutation: Record<string, unknown>;
    /** Variable mapping (JSON) */
    variableMapping: Record<string, unknown>;
    /** Headers (JSON) */
    headers?: Record<string, unknown>;
    /** Auth preset */
    auth?: string;
    /** Bearer token secret code */
    bearerTokenSecretCode?: string;
    /** Basic auth secret code */
    basicSecretCode?: string;
    /** Batch mode */
    batchMode?: string;
    /**
     * Max batch size
     * Chunk size when batchMode=batch
     */
    maxBatchSize?: number;
    /**
     * Retries
     * Number of retries for failed requests
     */
    retries?: number;
    /**
     * Retry delay (ms)
     * Delay between retries
     */
    retryDelayMs?: number;
    /**
     * Timeout (ms)
     * Request timeout in milliseconds
     */
    timeoutMs?: number;
}

/**
 * Upsert TaxRate by name; resolves tax category and zone by code.
 * @requires UpdateSettings
 * @entityType tax-rate
 */
export interface TaxRateUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'taxRateUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Name field
     * Field containing tax rate name
     */
    nameField: string;
    /**
     * Value field
     * Field containing tax rate percentage (0-100)
     */
    valueField: string;
    /**
     * Enabled field
     * Field indicating if rate is active
     */
    enabledField?: string;
    /**
     * Tax category code field
     * Field containing tax category code/name
     */
    taxCategoryCodeField: string;
    /**
     * Tax category ID field
     * Alternative: field containing tax category ID
     */
    taxCategoryIdField?: string;
    /**
     * Zone code field
     * Field containing zone code/name
     */
    zoneCodeField: string;
    /**
     * Zone ID field
     * Alternative: field containing zone ID
     */
    zoneIdField?: string;
}

/**
 * Upsert PaymentMethod by code; configure handler and eligibility checker.
 * @requires UpdateSettings
 * @entityType payment-method
 */
export interface PaymentMethodUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'paymentMethodUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Name field
     * Field containing payment method name
     */
    nameField: string;
    /**
     * Code field
     * Field containing unique payment method code
     */
    codeField: string;
    /**
     * Description field
     * Field containing description shown to customers
     */
    descriptionField?: string;
    /**
     * Enabled field
     * Field indicating if method is active
     */
    enabledField?: string;
    /** Handler field */
    handlerField: string;
    /** Checker field */
    checkerField?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name/description fields.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
}

/**
 * Upsert Channel by code; configure currencies, languages, and zones.
 * @requires UpdateSettings
 * @entityType channel
 */
export interface ChannelUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'channelUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Code field
     * Field containing unique channel code
     */
    codeField: string;
    /**
     * Token field
     * Field containing channel token (auto-generated if not provided)
     */
    tokenField?: string;
    /**
     * Default language code field
     * Field containing default language (e.g., "en")
     */
    defaultLanguageCodeField: string;
    /**
     * Available languages field
     * Field containing array of language codes
     */
    availableLanguageCodesField?: string;
    /**
     * Default currency code field
     * Field containing default currency (e.g., "USD")
     */
    defaultCurrencyCodeField: string;
    /**
     * Available currencies field
     * Field containing array of currency codes
     */
    availableCurrencyCodesField?: string;
    /**
     * Prices include tax field
     * Field indicating if prices include tax
     */
    pricesIncludeTaxField?: string;
    /**
     * Default tax zone code field
     * Field containing default tax zone code
     */
    defaultTaxZoneCodeField?: string;
    /**
     * Default shipping zone code field
     * Field containing default shipping zone code
     */
    defaultShippingZoneCodeField?: string;
    /**
     * Seller ID field
     * Field containing seller ID (for multi-vendor)
     */
    sellerIdField?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
}

/**
 * Upsert ShippingMethod by code; configure calculator, checker, and fulfillment handler. Supports multi-language translations and multi-channel assignment.
 * @requires UpdateShippingMethod
 * @entityType shipping-method
 */
export interface ShippingMethodUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'shippingMethodUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Name field
     * Field containing shipping method display name
     */
    nameField: string;
    /**
     * Code field
     * Field containing unique shipping method code
     */
    codeField: string;
    /**
     * Description field
     * Field containing description shown to customers
     */
    descriptionField?: string;
    /**
     * Fulfillment handler field
     * Field containing fulfillment handler code (e.g., "manual-fulfillment")
     */
    fulfillmentHandlerField: string;
    /** Calculator field */
    calculatorField: string;
    /** Checker field */
    checkerField?: string;
    /**
     * Custom fields field (object)
     * Record field containing custom field values (defaults to "customFields")
     */
    customFieldsField?: string;
    /**
     * Translations field
     * Record field containing multi-language translations (array or object map). Overrides name/description fields.
     */
    translationsField?: string;
    /**
     * Channels field (array/string)
     * Record field containing channel codes for dynamic per-record channel assignment (array or comma-separated)
     */
    channelsField?: string;
}

/**
 * Upsert CustomerGroup by name; assign customers by email.
 * @requires UpdateCustomer
 * @entityType customer-group
 */
export interface CustomerGroupUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'customerGroupUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Name field
     * Field containing unique customer group name
     */
    nameField: string;
    /**
     * Customer emails field
     * Field containing array of customer email addresses to add
     */
    customerEmailsField?: string;
}

/**
 * Upsert StockLocation by name; manage inventory locations and warehouses.
 * @requires UpdateCatalog
 * @entityType stock-location
 */
export interface StockLocationUpsertConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'stockLocationUpsert';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * Name field
     * Field containing stock location name
     */
    nameField: string;
    /**
     * Description field
     * Field containing location description
     */
    descriptionField?: string;
}

/**
 * Adjust stock levels for product variants by SKU. Supports stock location targeting.
 * @requires UpdateCatalog
 * @entityType inventory
 */
export interface InventoryAdjustConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'inventoryAdjust';
    /**
     * Load strategy
     * UPSERT: create or update. CREATE: only create new. UPDATE: only update existing.
     */
    strategy?: string;
    /**
     * SKU field
     * Field containing the product variant SKU
     */
    skuField: string;
    /**
     * Stock on hand field
     * Field containing the new absolute stock level
     */
    stockOnHandField: string;
    /**
     * Stock location name field
     * Field containing stock location name (uses default if not specified)
     */
    stockLocationNameField?: string;
    /**
     * Stock location ID field
     * Field containing stock location ID (alternative to name)
     */
    stockLocationIdField?: string;
    /**
     * Reason field
     * Field containing the adjustment reason
     */
    reasonField?: string;
}

/**
 * Delete entities (Product, Variant, Collection, Promotion, ShippingMethod, Customer, PaymentMethod, Facet, FacetValue, CustomerGroup, TaxRate, Asset, StockLocation) by slug, SKU, code, email, name, or ID.
 * @requires UpdateCatalog
 * @entityType product
 */
export interface EntityDeletionConfig {
    /** Loader adapter code (discriminator) */
    adapterCode: 'entityDeletion';
    /** Entity type */
    entityType?: string;
    /**
     * Identifier field
     * Record field containing the identifier to match (default depends on entity type)
     */
    identifierField?: string;
    /** Match by */
    matchBy?: string;
    /**
     * Cascade delete variants
     * Delete all variants when deleting a product (default: true)
     */
    cascadeVariants?: boolean;
    /** Channel code */
    channel?: string;
}

// ============================================================================
// UNION TYPES
// ============================================================================

/**
 * Union type of all loader configurations.
 * Use this for type-safe loader config handling with discriminated unions.
 */
export type LoaderConfig =
    | ProductUpsertConfig
    | VariantUpsertConfig
    | CustomerUpsertConfig
    | OrderUpsertConfig
    | OrderNoteConfig
    | StockAdjustConfig
    | ApplyCouponConfig
    | CollectionUpsertConfig
    | PromotionUpsertConfig
    | OrderTransitionConfig
    | AssetAttachConfig
    | AssetImportConfig
    | FacetUpsertConfig
    | FacetValueUpsertConfig
    | RestPostConfig
    | GraphqlMutationConfig
    | TaxRateUpsertConfig
    | PaymentMethodUpsertConfig
    | ChannelUpsertConfig
    | ShippingMethodUpsertConfig
    | CustomerGroupUpsertConfig
    | StockLocationUpsertConfig
    | InventoryAdjustConfig
    | EntityDeletionConfig
    | GenericLoaderConfig;

/**
 * Generic fallback config for custom loaders not in the registry
 */
export interface GenericLoaderConfig {
    adapterCode: string;
    [key: string]: unknown;
}

// ============================================================================
// HELPER TYPES
// ============================================================================

/**
 * Extract config type by adapter code.
 * Example: ConfigByCode<"productUpsert"> = ProductUpsertConfig
 */
export type ConfigByCode<T extends string> = T extends keyof LoaderConfigMap
    ? LoaderConfigMap[T]
    : GenericLoaderConfig;

/**
 * Mapping of adapter codes to their config types
 */
export interface LoaderConfigMap {
    productUpsert: ProductUpsertConfig;
    variantUpsert: VariantUpsertConfig;
    customerUpsert: CustomerUpsertConfig;
    orderUpsert: OrderUpsertConfig;
    orderNote: OrderNoteConfig;
    stockAdjust: StockAdjustConfig;
    applyCoupon: ApplyCouponConfig;
    collectionUpsert: CollectionUpsertConfig;
    promotionUpsert: PromotionUpsertConfig;
    orderTransition: OrderTransitionConfig;
    assetAttach: AssetAttachConfig;
    assetImport: AssetImportConfig;
    facetUpsert: FacetUpsertConfig;
    facetValueUpsert: FacetValueUpsertConfig;
    restPost: RestPostConfig;
    graphqlMutation: GraphqlMutationConfig;
    taxRateUpsert: TaxRateUpsertConfig;
    paymentMethodUpsert: PaymentMethodUpsertConfig;
    channelUpsert: ChannelUpsertConfig;
    shippingMethodUpsert: ShippingMethodUpsertConfig;
    customerGroupUpsert: CustomerGroupUpsertConfig;
    stockLocationUpsert: StockLocationUpsertConfig;
    inventoryAdjust: InventoryAdjustConfig;
    entityDeletion: EntityDeletionConfig;
}

/**
 * All loader adapter codes (for runtime validation)
 */
export const LOADER_CODES = [
    'productUpsert',
    'variantUpsert',
    'customerUpsert',
    'orderUpsert',
    'orderNote',
    'stockAdjust',
    'applyCoupon',
    'collectionUpsert',
    'promotionUpsert',
    'orderTransition',
    'assetAttach',
    'assetImport',
    'facetUpsert',
    'facetValueUpsert',
    'restPost',
    'graphqlMutation',
    'taxRateUpsert',
    'paymentMethodUpsert',
    'channelUpsert',
    'shippingMethodUpsert',
    'customerGroupUpsert',
    'stockLocationUpsert',
    'inventoryAdjust',
    'entityDeletion',
] as const;

/**
 * Type-safe loader code literal type
 */
export type LoaderCode = typeof LOADER_CODES[number];