import {
    HttpApiExtractorConfig,
    type CsvExtractorConfig,
    type JsonExtractorConfig,
    type ExcelExtractorConfig,
    type GraphqlExtractorConfig,
    type VendureQueryExtractorConfig,
    type WebhookExtractorConfig,
    type DatabaseExtractorConfig,
    type GenericExtractorConfig,
    type TypedExtractorConfig,
    type MapOperatorConfig,
    type TemplateOperatorConfig,
    type FilterOperatorConfig,
    type WhenOperatorConfig,
    type LookupOperatorConfig,
    type AggregateOperatorConfig,
    type DedupeOperatorConfig,
    type CoerceOperatorConfig,
    type EnrichOperatorConfig,
    type GenericOperatorConfig,
    type TypedOperatorConfig,
    type ProductUpsertLoaderConfig,
    type VariantUpsertLoaderConfig,
    type CustomerUpsertLoaderConfig,
    type StockAdjustLoaderConfig,
    type RestPostLoaderConfig,
    type OrderNoteLoaderConfig,
    type OrderTransitionLoaderConfig,
    type CollectionUpsertLoaderConfig,
    type AssetAttachLoaderConfig,
    type ApplyCouponLoaderConfig,
    type PromotionUpsertLoaderConfig,
    type GenericLoaderConfig,
    type TypedLoaderConfig,
    type CsvExportConfig,
    type JsonExportConfig,
    type XmlExportConfig,
    type GenericExporterConfig,
    type TypedExporterConfig,
    type GoogleMerchantFeedConfig,
    type MetaCatalogFeedConfig,
    type AmazonFeedConfig,
    type CustomFeedConfig,
    type GenericFeedConfig,
    type TypedFeedConfig,
    type SchemaValidatorConfig,
    type RouteConfig,
    type LoaderAdapterCode,
    LOADER_PERMISSIONS,
} from '../../shared/types';

export type {
    CsvExtractorConfig,
    JsonExtractorConfig,
    ExcelExtractorConfig,
    HttpApiExtractorConfig,
    GraphqlExtractorConfig,
    VendureQueryExtractorConfig,
    WebhookExtractorConfig,
    DatabaseExtractorConfig,
    GenericExtractorConfig,
    TypedExtractorConfig,
    MapOperatorConfig,
    TemplateOperatorConfig,
    FilterOperatorConfig,
    WhenOperatorConfig,
    LookupOperatorConfig,
    AggregateOperatorConfig,
    DedupeOperatorConfig,
    CoerceOperatorConfig,
    EnrichOperatorConfig,
    GenericOperatorConfig,
    TypedOperatorConfig,
    ProductUpsertLoaderConfig,
    VariantUpsertLoaderConfig,
    CustomerUpsertLoaderConfig,
    StockAdjustLoaderConfig,
    RestPostLoaderConfig,
    OrderNoteLoaderConfig,
    OrderTransitionLoaderConfig,
    CollectionUpsertLoaderConfig,
    AssetAttachLoaderConfig,
    ApplyCouponLoaderConfig,
    PromotionUpsertLoaderConfig,
    GenericLoaderConfig,
    TypedLoaderConfig,
    CsvExportConfig,
    JsonExportConfig,
    XmlExportConfig,
    GenericExporterConfig,
    TypedExporterConfig,
    GoogleMerchantFeedConfig,
    MetaCatalogFeedConfig,
    AmazonFeedConfig,
    CustomFeedConfig,
    GenericFeedConfig,
    TypedFeedConfig,
    SchemaValidatorConfig,
    RouteConfig,
    UpdateCatalogLoaders,
    UpdateCustomerLoaders,
    UpdateOrderLoaders,
    UpdatePromotionLoaders,
    UpdateDataHubSettingsLoaders,
    LoaderAdapterCode,
} from '../../shared/types';

export { LOADER_PERMISSIONS } from '../../shared/types';

export const Extractors = {
    csv: (config: Omit<CsvExtractorConfig, 'adapterCode'>): CsvExtractorConfig => ({ adapterCode: 'csv', ...config }),
    json: (config: Omit<JsonExtractorConfig, 'adapterCode'>): JsonExtractorConfig => ({ adapterCode: 'json', ...config }),
    excel: (config: Omit<ExcelExtractorConfig, 'adapterCode'>): ExcelExtractorConfig => ({ adapterCode: 'excel', ...config }),
    httpApi: (config: Omit<HttpApiExtractorConfig, 'adapterCode'>): HttpApiExtractorConfig => ({ adapterCode: 'httpApi', ...config }),
    graphql: (config: Omit<GraphqlExtractorConfig, 'adapterCode'>): GraphqlExtractorConfig => ({ adapterCode: 'graphql', ...config }),
    vendureQuery: (config: Omit<VendureQueryExtractorConfig, 'adapterCode'>): VendureQueryExtractorConfig => ({ adapterCode: 'vendureQuery', ...config }),
    webhook: (config: Omit<WebhookExtractorConfig, 'adapterCode'>): WebhookExtractorConfig => ({ adapterCode: 'webhook', ...config }),
    database: (config: Omit<DatabaseExtractorConfig, 'adapterCode'>): DatabaseExtractorConfig => ({ adapterCode: 'database', ...config }),
    custom: <T extends Record<string, unknown>>(adapterCode: string, config: T): GenericExtractorConfig => ({ adapterCode, ...config }),
};

export const Operators = {
    map: (config: Omit<MapOperatorConfig, 'adapterCode'>): MapOperatorConfig => ({ adapterCode: 'map', ...config }),
    template: (config: Omit<TemplateOperatorConfig, 'adapterCode'>): TemplateOperatorConfig => ({ adapterCode: 'template', ...config }),
    filter: (config: Omit<FilterOperatorConfig, 'adapterCode'>): FilterOperatorConfig => ({ adapterCode: 'filter', ...config }),
    when: (config: Omit<WhenOperatorConfig, 'adapterCode'>): WhenOperatorConfig => ({ adapterCode: 'when', ...config }),
    lookup: (config: Omit<LookupOperatorConfig, 'adapterCode'>): LookupOperatorConfig => ({ adapterCode: 'lookup', ...config }),
    aggregate: (config: Omit<AggregateOperatorConfig, 'adapterCode'>): AggregateOperatorConfig => ({ adapterCode: 'aggregate', ...config }),
    dedupe: (config: Omit<DedupeOperatorConfig, 'adapterCode'>): DedupeOperatorConfig => ({ adapterCode: 'dedupe', ...config }),
    coerce: (config: Omit<CoerceOperatorConfig, 'adapterCode'>): CoerceOperatorConfig => ({ adapterCode: 'coerce', ...config }),
    enrich: (config: Omit<EnrichOperatorConfig, 'adapterCode'>): EnrichOperatorConfig => ({ adapterCode: 'enrich', ...config }),
    custom: <T extends Record<string, unknown>>(adapterCode: string, config: T): GenericOperatorConfig => ({ adapterCode, ...config }),
};

export const Loaders = {
    productUpsert: (config: Omit<ProductUpsertLoaderConfig, 'adapterCode'>): ProductUpsertLoaderConfig => ({ adapterCode: 'productUpsert', ...config }),
    variantUpsert: (config: Omit<VariantUpsertLoaderConfig, 'adapterCode'>): VariantUpsertLoaderConfig => ({ adapterCode: 'variantUpsert', ...config }),
    customerUpsert: (config: Omit<CustomerUpsertLoaderConfig, 'adapterCode'>): CustomerUpsertLoaderConfig => ({ adapterCode: 'customerUpsert', ...config }),
    stockAdjust: (config: Omit<StockAdjustLoaderConfig, 'adapterCode'>): StockAdjustLoaderConfig => ({ adapterCode: 'stockAdjust', ...config }),
    restPost: (config: Omit<RestPostLoaderConfig, 'adapterCode'>): RestPostLoaderConfig => ({ adapterCode: 'restPost', ...config }),
    orderNote: (config: Omit<OrderNoteLoaderConfig, 'adapterCode'>): OrderNoteLoaderConfig => ({ adapterCode: 'orderNote', ...config }),
    orderTransition: (config: Omit<OrderTransitionLoaderConfig, 'adapterCode'>): OrderTransitionLoaderConfig => ({ adapterCode: 'orderTransition', ...config }),
    collectionUpsert: (config: Omit<CollectionUpsertLoaderConfig, 'adapterCode'>): CollectionUpsertLoaderConfig => ({ adapterCode: 'collectionUpsert', ...config }),
    assetAttach: (config: Omit<AssetAttachLoaderConfig, 'adapterCode'>): AssetAttachLoaderConfig => ({ adapterCode: 'assetAttach', ...config }),
    applyCoupon: (config: Omit<ApplyCouponLoaderConfig, 'adapterCode'>): ApplyCouponLoaderConfig => ({ adapterCode: 'applyCoupon', ...config }),
    promotionUpsert: (config: Omit<PromotionUpsertLoaderConfig, 'adapterCode'>): PromotionUpsertLoaderConfig => ({ adapterCode: 'promotionUpsert', ...config }),
    custom: <T extends Record<string, unknown>>(adapterCode: string, config: T): GenericLoaderConfig => ({ adapterCode, ...config }),
};

export const Feeds = {
    googleMerchant: (config: Omit<GoogleMerchantFeedConfig, 'adapterCode'>): GoogleMerchantFeedConfig => ({ adapterCode: 'googleMerchant', ...config }),
    metaCatalog: (config: Omit<MetaCatalogFeedConfig, 'adapterCode'>): MetaCatalogFeedConfig => ({ adapterCode: 'metaCatalog', ...config }),
    amazon: (config: Omit<AmazonFeedConfig, 'adapterCode'>): AmazonFeedConfig => ({ adapterCode: 'amazonFeed', ...config }),
    customFeed: (config: Omit<CustomFeedConfig, 'adapterCode'>): CustomFeedConfig => ({ adapterCode: 'customFeed', ...config }),
    custom: <T extends Record<string, unknown>>(adapterCode: string, config: T): GenericFeedConfig => ({ adapterCode, ...config }),
};
