import {
    AlertTriangle,
    ArrowRight,
    Ban,
    BarChart,
    Box,
    CheckCircle,
    CheckCircle2,
    ClipboardList,
    Clock,
    Cloud,
    Code,
    Cog,
    Currency,
    Database,
    DollarSign,
    Download,
    File,
    FileCode,
    FileJson,
    FileOutput,
    FileSpreadsheet,
    FileText,
    Filter,
    Folder,
    FolderOpen,
    FolderTree,
    GitBranch,
    Globe,
    HardDrive,
    Image,
    Layers,
    Mail,
    MapPin,
    MessageSquare,
    Package,
    Pause,
    Percent,
    Play,
    Receipt,
    RefreshCw,
    Rss,
    Search,
    Send,
    Server,
    Settings,
    Sheet,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Sparkles,
    Store,
    Tag,
    TimerOff,
    Trash2,
    Upload,
    Users,
    Warehouse,
    Webhook,
    X,
    XCircle,
    Zap,
    type LucideIcon,
} from 'lucide-react';

const ICONS = {
    'alert-triangle': AlertTriangle,
    'arrow-right': ArrowRight,
    ban: Ban,
    'bar-chart': BarChart,
    box: Box,
    'check-circle': CheckCircle,
    'check-circle-2': CheckCircle2,
    'clipboard-list': ClipboardList,
    clock: Clock,
    cloud: Cloud,
    code: Code,
    cog: Cog,
    'currency-exchange': Currency,
    database: Database,
    'dollar-sign': DollarSign,
    download: Download,
    file: File,
    'file-code': FileCode,
    'file-json': FileJson,
    'file-output': FileOutput,
    'file-spreadsheet': FileSpreadsheet,
    'file-text': FileText,
    filter: Filter,
    folder: Folder,
    'folder-open': FolderOpen,
    'folder-tree': FolderTree,
    'git-branch': GitBranch,
    globe: Globe,
    'hard-drive': HardDrive,
    image: Image,
    layers: Layers,
    mail: Mail,
    'map-pin': MapPin,
    memory: Database,
    'message-square': MessageSquare,
    package: Package,
    pause: Pause,
    percent: Percent,
    play: Play,
    receipt: Receipt,
    refresh: RefreshCw,
    'refresh-cw': RefreshCw,
    rss: Rss,
    search: Search,
    send: Send,
    server: Server,
    settings: Settings,
    sheet: Sheet,
    shield: Shield,
    'shield-check': ShieldCheck,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    sparkles: Sparkles,
    store: Store,
    tag: Tag,
    'timer-off': TimerOff,
    'trash-2': Trash2,
    upload: Upload,
    users: Users,
    warehouse: Warehouse,
    webhook: Webhook,
    x: X,
    'x-circle': XCircle,
    zap: Zap,
} as const satisfies Readonly<Record<string, LucideIcon>>;

function normalizeIconName(name: string): string {
    return name
        .trim()
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
        .toLowerCase();
}

export function resolveIconName(name: string | undefined | null): LucideIcon | undefined {
    if (!name) return undefined;
    return ICONS[normalizeIconName(name) as keyof typeof ICONS];
}
