export const PIMCORE_EXTRACTOR_LIMITS = {
    DEFAULT_MAX_PAGES: 100,
    DEFAULT_MAX_RETRIES: 3,
    DEFAULT_PAGE_SIZE: 100,
    DEFAULT_RETRY_DELAY_MS: 1_000,
    DEFAULT_TIMEOUT_MS: 30_000,
    MAX_ERROR_LENGTH: 500,
    MAX_PAGES: 10_000,
    MAX_PAGE_SIZE: 1_000,
    MAX_RETRIES: 10,
    MAX_RETRY_DELAY_MS: 60_000,
    MAX_TIMEOUT_MS: 300_000,
} as const;

export const PIMCORE_WEBHOOK_KEY_SECRET = 'pimcore-webhook-key';
export const PIMCORE_SOURCE_ORIGIN_FIELD = '_pimcoreSourceOrigin';
